sparksuite/w3c-css-validator

.travis.yml
package.json
src/index.ts
test/index.test.ts
yarn.lock

Integrate both Jest & Codecov. Modeled after Waterfall CLI.
Closes #5
Closes #3

Integrate Jest & Codecov

---

.github/workflows/main.yml

This MR applies some small tweaks and changes to our initial GitHub Actions implementation.

Tweak GitHub Actions

---

.github/workflows/main.yml
package.json

This modifies the configuration for Prettier to lint and format YAML files as well.

Lint and format YAML files too

---

.github/workflows/main.yml

Trying to nail down why it isn't being triggered...

Comment out a lot of the workflow

---

.github/workflows/main.yml

This should work now. Apparently `$default-branch` meant replace it with the default. It wasn't actually pulling in the default dynamically.

Uncomment stuff

---

src/validate-text.ts
test/index.test.ts

Add input validation to the `validateText()` function

---

README.md

Write the README

---

src/validate-text.ts

By explicitly setting the `profile` option to CSS 3, it won't default to CSS 2.

Change the profile to CSS3

---

README.md

This fixes some variable names in the README which were inaccurate/inconsistent.

Fix variable names in README

---

CONTRIBUTING.md
package.json
website/docusaurus.config.js

Fix Docusaurus base URL

---

eslint.src.json
eslint.tests.json
eslint.website.json
package.json
src/.eslintrc.json
tests/.eslintrc.json
website/.eslintrc.json
website/docs/getting-started/import.md
website/src/pages/index.tsx

Primarily this refactors how we use ESLint to depend on nested configuration files with default names. But also, this polishes up some other areas, too.

General polish

---

package.json

This updates the homepage in the package file to the new website.

Update the homepage

---

website/package.json
website/yarn.lock
yarn.lock

Update dependencies at the root, and within the `website/` directory.

Update a variety of dependencies

---

README.md

This improves the README's badges, along with a small tweak to one of the perks. These are taken from our work on Rugged.

Improve the README, following conventions from other projects

---

.eslintrc.json
eslint.base.json
package.json
src/.eslintrc.json
src/index.test.ts
src/validate-text.test.ts
test-projects/browser/src/index.ts

This PR fixes ESLint's configuration, which brought to light issues with the code, which have now been fixed.

Fix ESLint config + problems in the code

---

website/src/css/custom.css
website/src/pages/styles.module.css

This PR tweaks the appearance of the website to align with our other repos. Specifically, it darkens the green and adjusts the look of the "Get started" button.

Tweak website appearance

---

.gitignore
tsconfig.base.json
website/.eslintrc.json

This PR fixes three configuration-like files to address bugs and standardize these files so that they're consistent with our other OSS projects.

Fix a handful of config files

---

package.json
src/retrieve-validation/browser.ts
src/retrieve-validation/index.ts
src/retrieve-validation/node.ts
src/validate-text.test.ts
src/validate-text.ts
website/docs/functions/validate-text.md

This pull request adds functionality to enable a custom timeout in both node and browser environments.
Closes #56

Added timeout option

---

package.json
src/retrieve-validation/browser.ts
src/retrieve-validation/node.ts
test-projects/browser/webpack.config.js

This pull request introduces a new method of getting the size of the parameters in bytes, that should be more accurate and allow for characters who use more than one byte.
Closes #132

Utilized method of getting more accurate byte length

---

website/src/pages/index.tsx

Closes #144 
Hopefully, the third time's a charm! Thanks again for all your time reviewing this with me :)

fixed typo on homepage

---

src/retrieve-validation/browser.test.ts
src/retrieve-validation/node.test.ts

Fixed incorrect function imports

---

package.json

Bump the minor version
